# MLS Award Database

In [1]:
import pandas as pd
import numpy as np

## Team Name Data Dictionary

In [2]:
# MLS Team Information
url_teams = "https://en.wikipedia.org/wiki/Major_League_Soccer"
html_teams = pd.read_html(url_teams)

html_teams[1].head()

                Team  ...           Head coach
  Eastern Conference  ...   Eastern Conference
0  Atlanta United FC  ...       Gonzalo Pineda
1       Charlotte FC  ...  Christian Lattanzio
2    Chicago Fire FC  ...        Frank Klopas3
3      FC Cincinnati  ...           Pat Noonan
4      Columbus Crew  ...       Wilfried Nancy

[5 rows x 6 columns]

In [3]:
# Remove 'Image', 'Other nominees', 'Position' and 'Ref(s)' columns
# df.drop(columns =['C', 'D'])
# df = df.drop(df[df['age'] > 30].index)

team_names = html_teams[1]

print(team_names.columns)

MultiIndex([(      'Team', 'Eastern Conference'),
            (  'Location', 'Eastern Conference'),
            (   'Stadium', 'Eastern Conference'),
            (  'Capacity', 'Eastern Conference'),
            (    'Joined', 'Eastern Conference'),
            ('Head coach', 'Eastern Conference')],
           )

In [4]:
# Drop 'Eastern Conference' level and row titled 'Western Conference'
team_names = team_names.droplevel(1, axis=1)
team_names = team_names.drop([15])

team_names.head(20)

                      Team  ...           Head coach
0        Atlanta United FC  ...       Gonzalo Pineda
1             Charlotte FC  ...  Christian Lattanzio
2          Chicago Fire FC  ...        Frank Klopas3
3            FC Cincinnati  ...           Pat Noonan
4            Columbus Crew  ...       Wilfried Nancy
5              D.C. United  ...               Vacant
6           Inter Miami CF  ...      Gerardo Martino
7              CF Montréal  ...        Hernán Losada
8             Nashville SC  ...           Gary Smith
9   New England Revolution  ...     Richie Williams3
10        New York City FC  ...         Nick Cushing
11      New York Red Bulls  ...         Troy Lesesne
12         Orlando City SC  ...         Óscar Pareja
13      Philadelphia Union  ...           Jim Curtin
14              Toronto FC  ...         John Herdman
16               Austin FC  ...           Josh Wolff
17         Colorado Rapids  ...        Chris Little3
18               FC Dallas  ...         Nico Estévez
19       Houston Dynamo FC  ...            Ben Olsen
20    Sporting Kansas City  ...         Peter Vermes

[20 rows x 6 columns]

In [5]:
team_names.dtypes

Team          object
Location      object
Stadium       object
Capacity      object
Joined        object
Head coach    object
dtype: object

In [6]:
# Convert 'Capacity' column to an integer
team_names['Capacity'] = team_names['Capacity'].astype(int)

In [7]:
# Former teams to be included in dictionary
former_teams = html_teams[3]

former_teams.head()

               Team                  Location  ... Joined  Final season
0  Tampa Bay Mutiny            Tampa, Florida  ...   1996          2001
1      Miami Fusion  Fort Lauderdale, Florida  ...   1998          2001
2        Chivas USA        Carson, California  ...   2005          2014

[3 rows x 6 columns]

In [8]:
former_teams.dtypes

Team            object
Location        object
Stadium         object
Capacity         int64
Joined           int64
Final season     int64
dtype: object

In [9]:
# Combine the two team lists, drop index
# df1.merge(df2, on=['col1', 'col2'])
# result = pd.concat([df1, df2], axis=1)

team_names = pd.concat([former_teams, team_names], axis=0).reset_index(drop=True)
team_names.head(20)

                      Team  ...           Head coach
0         Tampa Bay Mutiny  ...                  NaN
1             Miami Fusion  ...                  NaN
2               Chivas USA  ...                  NaN
3        Atlanta United FC  ...       Gonzalo Pineda
4             Charlotte FC  ...  Christian Lattanzio
5          Chicago Fire FC  ...        Frank Klopas3
6            FC Cincinnati  ...           Pat Noonan
7            Columbus Crew  ...       Wilfried Nancy
8              D.C. United  ...               Vacant
9           Inter Miami CF  ...      Gerardo Martino
10             CF Montréal  ...        Hernán Losada
11            Nashville SC  ...           Gary Smith
12  New England Revolution  ...     Richie Williams3
13        New York City FC  ...         Nick Cushing
14      New York Red Bulls  ...         Troy Lesesne
15         Orlando City SC  ...         Óscar Pareja
16      Philadelphia Union  ...           Jim Curtin
17              Toronto FC  ...         John Herdman
18               Austin FC  ...           Josh Wolff
19         Colorado Rapids  ...        Chris Little3

[20 rows x 7 columns]

In [10]:
# List of Team Names
# df['column_name'].tolist()
team_list = team_names['Team'].tolist()

print(team_list)

['Tampa Bay Mutiny', 'Miami Fusion', 'Chivas USA', 'Atlanta United FC', 'Charlotte FC', 'Chicago Fire FC', 'FC Cincinnati', 'Columbus Crew', 'D.C. United', 'Inter Miami CF', 'CF Montréal', 'Nashville SC', 'New England Revolution', 'New York City FC', 'New York Red Bulls', 'Orlando City SC', 'Philadelphia Union', 'Toronto FC', 'Austin FC', 'Colorado Rapids', 'FC Dallas', 'Houston Dynamo FC', 'Sporting Kansas City', 'LA Galaxy', 'Los Angeles FC', 'Minnesota United FC', 'Portland Timbers', 'Real Salt Lake', 'San Jose Earthquakes', 'Seattle Sounders FC', 'St. Louis City SC', 'Vancouver Whitecaps FC']

In [11]:
# Generate team name to 3-4 letter abbreviation mapping
# Reference: ChatGPT (also: https://www.shrpsports.com/mls/explain.htm)
# Update list: ShrpSports (https://www.shrpsports.com/mls/explain.htm)
mls_teams = {
    "ATL": "Atlanta United FC",
    "AUS": "Austin FC",
    "CHI": "Chicago Fire FC",
    "CHV": "Chivas USA",
    "CIN": "FC Cincinnati",
    "COL": "Colorado Rapids",
    "CLB": "Columbus Crew",
    "CLT": "Charlotte FC",
    "DBU": "Dallas Burn",
    "DC": "D.C. United",
    "DAL": "FC Dallas",
    "HOU": "Houston Dynamo FC",
    "MIA": "Inter Miami CF",
    "MIF": "Miami Fusion",
    "KWZ": "Kansas City Wiz",
    "KCW": "Kansas City Wizards",
    "LAG": "LA Galaxy",
    "LAFC": "Los Angeles FC",
    "MET": "NY/NJ MetroStars",
    "MIN": "Minnesota United FC",
    "MTI": "Montreal Impact",
    "MTL": "CF Montréal",
    "NSH": "Nashville SC",
    "NE": "New England Revolution",
    "NYCFC": "New York City FC",
    "NYRB": "New York Red Bulls",
    "ORL": "Orlando City SC",
    "PHI": "Philadelphia Union",
    "POR": "Portland Timbers",
    "RSL": "Real Salt Lake",
    "SJ": "San Jose Earthquakes",
    "SEA": "Seattle Sounders FC",
    "SKC": "Sporting Kansas City",
    "STL": "St. Louis City SC",
    "TOR": "Toronto FC",
    "TB": "Tampa Bay Mutiny",
    "VAN": "Vancouver Whitecaps FC"
}

# Accessing the data dictionary
team_abbreviation = "SEA"
team_name = mls_teams.get(team_abbreviation, "Team not found")

# Print the team name for the given abbreviation
print(f"The team abbreviation '{team_abbreviation}' corresponds to the team '{team_name}'")

The team abbreviation 'SEA' corresponds to the team 'Seattle Sounders FC'

## Scrape for MLS trophies and awards

### Best MLS Player ESPY Award
Annual MLS award honoring the achievements of an individual from the MLS, first awarded in 2006 and presented to the MLS player adjudged to be the best in a given calendar year at the annual ESPY Awards ceremony in Los Angeles. Balloting for the award is undertaken by fans over the Internet from between three and five nominees selected by the ESPN Select Nominating Committee, which is composed by a panel of experts. 

_NOTE: It is conferred in July to reflect performance and achievement over the preceding twelve months, which generally includes a portion of each of two MLS seasons_

In [12]:
# Best MLS Player ESPY Award winners and nominees (2006 - 2022)
url_espy = "https://en.wikipedia.org/wiki/Best_MLS_Player_ESPY_Award"
html_espy = pd.read_html(url_espy)

html_espy[1].head()

   Year Image  ...                                     Other nominees    Ref(s)
0  2006   NaN  ...  Dwayne De Rosario ( CAN) – San Jose Earthquake...    [5][2]
1  2007   NaN  ...  Jeff Cunningham ( USA) – Toronto FC Christian ...    [8][9]
2  2008   NaN  ...  Juan Pablo Ángel ( COL) – New York Red Bulls C...   [9][10]
3  2009   NaN  ...  Juan Pablo Ángel ( COL) – New York Red Bulls J...      [11]
4  2010   NaN  ...  Conor Casey ( USA) – Colorado Rapids Jeff Cunn...  [12][13]

[5 rows x 8 columns]

In [13]:
espy_award = html_espy[1]

espy_award.dtypes

Year               int64
Image             object
Player            object
Nation            object
Team              object
Position          object
Other nominees    object
Ref(s)            object
dtype: object

In [14]:
# Remove 'Image', 'Other nominees', 'Position' and 'Ref(s)' columns
# df.drop(columns =['C', 'D'])
espy_award = espy_award.drop(columns =['Image', 'Position', 'Ref(s)'])

# Remove 2020 Year (No award due to COVID-19)
# df = df.drop(df[df['age'] > 30].index)
espy_award = espy_award.drop(espy_award[espy_award['Year'] == 2020].index)

# Remove reference no. in Player
# df['name'] = df['name'].str.split('_').str[0]
# espy_award['Player'] = espy_award['Player'].str.split('(').str[0]

espy_award.head(20)

    Year  ...                                     Other nominees
0   2006  ...  Dwayne De Rosario ( CAN) – San Jose Earthquake...
1   2007  ...  Jeff Cunningham ( USA) – Toronto FC Christian ...
2   2008  ...  Juan Pablo Ángel ( COL) – New York Red Bulls C...
3   2009  ...  Juan Pablo Ángel ( COL) – New York Red Bulls J...
4   2010  ...  Conor Casey ( USA) – Colorado Rapids Jeff Cunn...
5   2011  ...  Edson Buddle ( USA) – LA Galaxy David Ferreira...
6   2012  ...  Dwayne De Rosario ( CAN) – D.C. United Brad Da...
7   2013  ...  Chris Wondolowski ( USA) – San Jose Earthquake...
8   2014  ...  Marco Di Vaio ( ITA) – Montreal Impact Robbie ...
9   2015  ...  Obafemi Martins ( NGA) – Seattle Sounders FC L...
10  2016  ...  Kei Kamara ( SLE) – New England Revolution Lau...
11  2017  ...  Andre Blake ( JAM) – Philadelphia Union Stefan...
12  2018  ...  Tim Melia ( USA) – Sporting Kansas City Ike Op...
13  2019  ...  Josef Martínez ( VEN) – Atlanta United FC Aaro...
15  2021  ...  Andre Blake ( JAM) – Philadelphia Union Alejan...
16  2022  ...  Valentín Castellanos ( ARG) – New York City FC...

[16 rows x 5 columns]

In [15]:
import pandas as pd
import re
from fuzzywuzzy import fuzz

# Function to replace values with keys and add a delimiter with fuzzy matching
def delimit_multiplayer_cols(value, data_dict, delimiter, use_fuzzy=True, fuzzy_threshold=60):
    for key, replacement in data_dict.items():
        if use_fuzzy:
            if fuzz.ratio(value, replacement) > fuzzy_threshold:
                value = re.sub(r'\b' + re.escape(replacement) + r'\b', replacement + delimiter, value)
        else:
            value = re.sub(r'\b' + re.escape(replacement) + r'\b', replacement + delimiter, value)

    return value


# Function to replace values with keys and add a delimiter
#def delimit_multiplayer_cols(value, data_dict, delimiter):
#    for key, replacement in data_dict.items():
#        value = re.sub(r'\b' + re.escape(replacement) + r'\b', replacement + delimiter, value)
#
#    return value

delimiter = '|'

# Apply the function to the DataFrame column
espy_award['Other nominees'] = espy_award['Other nominees'].apply(lambda x: delimit_multiplayer_cols(x, mls_teams, delimiter, use_fuzzy=False))

espy_award.head()

   Year  ...                                     Other nominees
0  2006  ...  Dwayne De Rosario ( CAN) – San Jose Earthquake...
1  2007  ...  Jeff Cunningham ( USA) – Toronto FC| Christian...
2  2008  ...  Juan Pablo Ángel ( COL) – New York Red Bulls| ...
3  2009  ...  Juan Pablo Ángel ( COL) – New York Red Bulls| ...
4  2010  ...  Conor Casey ( USA) – Colorado Rapids| Jeff Cun...

[5 rows x 5 columns]

In [16]:
# Split the 'Other nominees' column at '|'
espy_award = espy_award.assign(Other_nominees=espy_award['Other nominees'].str.split('|'))

# Create a list of dictionaries with the desired values
new_rows = []
for index, row in espy_award.iterrows():
    year = row['Year']
    for nominee in row['Other_nominees']:
        parts = re.split(r' – | \(|\) – ', nominee.strip())
        
        if len(parts) == 3:
            player, nation, team = parts
        elif len(parts) == 2:
            player, team = parts
            nation = ''
        else:
            continue  # Skip this entry as it doesn't have enough information
        
        new_row = {
            'Year': year,
            'Player': player,
            'Nation': nation,
            'Team': team,
        }
        new_rows.append(new_row)

# Create a new DataFrame from the list of dictionaries
espy_othernoms = pd.DataFrame(new_rows)

# Print the new DataFrame
espy_othernoms.head()

   Year             Player Nation                    Team
0  2006  Dwayne De Rosario    CAN    San Jose Earthquakes
1  2006       Jaime Moreno    BOL             D.C. United
2  2006    Taylor Twellman    USA  New England Revolution
3  2007    Jeff Cunningham    USA              Toronto FC
4  2007    Christian Gómez    ARG             D.C. United

In [17]:
espy_award.head(10)

   Year  ...                                     Other_nominees
0  2006  ...  [Dwayne De Rosario ( CAN) – San Jose Earthquak...
1  2007  ...  [Jeff Cunningham ( USA) – Toronto FC,  Christi...
2  2008  ...  [Juan Pablo Ángel ( COL) – New York Red Bulls,...
3  2009  ...  [Juan Pablo Ángel ( COL) – New York Red Bulls,...
4  2010  ...  [Conor Casey ( USA) – Colorado Rapids,  Jeff C...
5  2011  ...  [Edson Buddle ( USA) – LA Galaxy,  David Ferre...
6  2012  ...  [Dwayne De Rosario ( CAN) – D.C. United,  Brad...
7  2013  ...  [Chris Wondolowski ( USA) – San Jose Earthquak...
8  2014  ...  [Marco Di Vaio ( ITA) – Montreal Impact,  Robb...
9  2015  ...  [Obafemi Martins ( NGA) – Seattle Sounders FC,...

[10 rows x 6 columns]

In [18]:
espy_award['Player'] = espy_award['Player'].str.replace(r'\s*\(.*\)', '', regex=True)
espy_award['Player'] = espy_award['Player'].str.replace('†', '', regex=True)
espy_award = espy_award.drop(columns = ['Other nominees', 'Other_nominees'])
espy_award['ESPY Winner'] = 1

espy_award.head(10)

   Year          Player Nation                Team  ESPY Winner
0  2006  Landon Donovan    USA           LA Galaxy            1
1  2007  Landon Donovan    USA           LA Galaxy            1
2  2008   David Beckham    ENG           LA Galaxy            1
3  2009  Landon Donovan    USA           LA Galaxy            1
4  2010  Landon Donovan    USA           LA Galaxy            1
5  2011  Landon Donovan    USA           LA Galaxy            1
6  2012   David Beckham    ENG           LA Galaxy            1
7  2013   Thierry Henry    FRA  New York Red Bulls            1
8  2014      Tim Cahill    AUS  New York Red Bulls            1
9  2015    Robbie Keane    IRL           LA Galaxy            1

In [19]:
espy_othernoms.dtypes

Year       int64
Player    object
Nation    object
Team      object
dtype: object

In [20]:
# Merge espy_othernoms data
espy_award = pd.concat([espy_award, espy_othernoms])
espy_award['ESPY Finalist'] = 1
espy_award['ESPY Winner'] = espy_award['ESPY Winner'].fillna(0)

espy_award.head(20)

    Year              Player  ... ESPY Winner ESPY Finalist
0   2006      Landon Donovan  ...         1.0             1
1   2007      Landon Donovan  ...         1.0             1
2   2008       David Beckham  ...         1.0             1
3   2009      Landon Donovan  ...         1.0             1
4   2010      Landon Donovan  ...         1.0             1
5   2011      Landon Donovan  ...         1.0             1
6   2012       David Beckham  ...         1.0             1
7   2013       Thierry Henry  ...         1.0             1
8   2014          Tim Cahill  ...         1.0             1
9   2015        Robbie Keane  ...         1.0             1
10  2016  Sebastian Giovinco  ...         1.0             1
11  2017         David Villa  ...         1.0             1
12  2018     Nemanja Nikolić  ...         1.0             1
13  2019  Zlatan Ibrahimović  ...         1.0             1
15  2021         Diego Rossi  ...         1.0             1
16  2022         Carlos Vela  ...         1.0             1
0   2006   Dwayne De Rosario  ...         0.0             1
1   2006        Jaime Moreno  ...         0.0             1
2   2006     Taylor Twellman  ...         0.0             1
3   2007     Jeff Cunningham  ...         0.0             1

[20 rows x 6 columns]

In [21]:
espy_award.dtypes

Year               int64
Player            object
Nation            object
Team              object
ESPY Winner      float64
ESPY Finalist      int64
dtype: object

### MLS Best XI
Annual acknowledgment of the best eleven players in MLS. The selection is determined by a collection of media, players, and MLS club technical staffs

In [22]:
# MLS Best XI
url_bestXI = "https://en.wikipedia.org/wiki/MLS_Best_XI"
html_bestXI = pd.read_html(url_bestXI)

html_bestXI[0].head()

       Year  ...                                           Forwards
0  1996 [2]  ...  Eduardo Hurtado, LA Galaxy  Roy Lassiter, Tamp...
1  1997 [2]  ...  Ronald Cerritos, San Jose  Jaime Moreno, D.C. ...
2  1998 [2]  ...        Stern John, Columbus  Cobi Jones, LA Galaxy
3  1999 [2]  ...  Jason Kreis, Dallas  Jaime Moreno, D.C. United...
4  2000 [2]  ...  Mamadou Diallo, Tampa Bay  Clint Mathis, Metro...

[5 rows x 5 columns]

In [23]:
bestXI_award = html_bestXI[0]

bestXI_award.dtypes

Year           object
Goalkeeper     object
Defenders      object
Midfielders    object
Forwards       object
dtype: object

In [24]:
# Remove reference numbers in () and [] from dataframe
import re
# df['text'] = df['text'].str.replace(r'\(.*\)', '', regex=True)
bestXI_award['Year'] = bestXI_award['Year'].str.replace(r'\s*\[.*?\]', '', regex=True)
bestXI_award['Goalkeeper'] = bestXI_award['Goalkeeper'].str.replace(r'\s*\(.*\)', '', regex=True)
bestXI_award['Defenders'] = bestXI_award['Defenders'].str.replace(r'\s*\(.*\)', '', regex=True)
bestXI_award['Midfielders'] = bestXI_award['Midfielders'].str.replace(r'\s*\(.*\)', '', regex=True)
bestXI_award['Forwards'] = bestXI_award['Forwards'].str.replace(r'\s*\(.*\)', '', regex=True)
bestXI_award.head(20)

    Year  ...                                           Forwards
0   1996  ...  Eduardo Hurtado, LA Galaxy  Roy Lassiter, Tamp...
1   1997  ...  Ronald Cerritos, San Jose  Jaime Moreno, D.C. ...
2   1998  ...        Stern John, Columbus  Cobi Jones, LA Galaxy
3   1999  ...     Jason Kreis, Dallas  Jaime Moreno, D.C. United
4   2000  ...  Mamadou Diallo, Tampa Bay  Clint Mathis, Metro...
5   2001  ...  Alex Pineda Chacón, Miami  Diego Serna, Miami ...
6   2002  ...  Jeff Cunningham, Columbus  Carlos Ruiz, LA Gal...
7   2003  ...        Ante Razov, Chicago  John Spencer, Colorado
8   2004  ...   Brian Ching, San Jose  Jaime Moreno, D.C. United
9   2005  ...                          Jaime Moreno, D.C. United
10  2006  ...                         Jeff Cunningham, Salt Lake
11  2007  ...  Juan Pablo Angel, Red Bulls  Luciano Emílio, D...
12  2008  ...    Kenny Cooper, Dallas  Landon Donovan, LA Galaxy
13  2009  ...     Conor Casey, Colorado  Jeff Cunningham, Dallas
14  2010  ...  Edson Buddle, LA Galaxy  Chris Wondolowski, Sa...
15  2011  ...  Thierry Henry, Red Bulls  Chris Wondolowski, S...
16  2012  ...                           Thierry Henry, Red Bulls
17  2013  ...  Marco Di Vaio, Montreal  Robbie Keane, LA Gala...
18  2014  ...  Robbie Keane, LA Galaxy  Obafemi Martins, Seat...
19  2015  ...  Sebastian Giovinco, Toronto  Kei Kamara, Colum...

[20 rows x 5 columns]

In [25]:
import pandas as pd
import re

# Delimit the multiplayer columns
bestXI_award['Defenders'] = bestXI_award['Defenders'].str.replace('  ', '| ', regex=True)
bestXI_award['Midfielders'] = bestXI_award['Midfielders'].str.replace('  ', '| ', regex=True)
bestXI_award['Forwards'] = bestXI_award['Forwards'].str.replace('  ', '| ', regex=True)

bestXI_award.head()

   Year  ...                                           Forwards
0  1996  ...  Eduardo Hurtado, LA Galaxy| Roy Lassiter, Tamp...
1  1997  ...  Ronald Cerritos, San Jose| Jaime Moreno, D.C. ...
2  1998  ...        Stern John, Columbus| Cobi Jones, LA Galaxy
3  1999  ...     Jason Kreis, Dallas| Jaime Moreno, D.C. United
4  2000  ...  Mamadou Diallo, Tampa Bay| Clint Mathis, Metro...

[5 rows x 5 columns]

In [26]:
# Remodel function to create new_rows and concat to bestXI_award df
# Latest bestXI_award: 'Year', 'Player', 'Team', and 'Position'
def create_new_dataframe_from_columns(df, columns):
    new_rows = []
    
    for index, row in df.iterrows():
        year = row['Year']
        
        for column in columns:
            column_values = row[column]
            
            if pd.notna(column_values):
                # Split the column values at '|'
                values_list = column_values.split('|')
                
                for nominee in values_list:
                    parts = re.split(r'\|', nominee.strip())
                    
                    for part in parts:
                        player_team = part.strip().split(', ')
                        if len(player_team) == 2:
                            player, team = player_team
                            new_row = {
                                'Year': year,
                                'Player': player,
                                'Team': team,
                            }
                            new_rows.append(new_row)

    new_df = pd.DataFrame(new_rows)
    return new_df

In [27]:
# Iterate through columns
columns_to_process = ['Goalkeeper', 'Defenders', 'Midfielders', 'Forwards']
bestXI_players = create_new_dataframe_from_columns(bestXI_award, columns_to_process)
bestXI_players.head()

   Year               Player       Team
0  1996            Mark Dodd     Dallas
1  1996       Leonel Álvarez     Dallas
2  1996           John Doyle   San Jose
3  1996         Robin Fraser  LA Galaxy
4  1996  Mauricio Cienfuegos  LA Galaxy

In [28]:
SELECT * FROM bestXI_players WHERE Player = 'Landon Donovan'

   Year          Player       Team
0  2008  Landon Donovan  LA Galaxy
1  2012  Landon Donovan  LA Galaxy
2  2014  Landon Donovan  LA Galaxy

In [29]:
bestXI_award.dtypes

Year           object
Goalkeeper     object
Defenders      object
Midfielders    object
Forwards       object
dtype: object

### MLS Comeback Player of the Year Award
MLS award established in 2000. The award is voted on by media, MLS players and club management. It is presented to a player who showed impressive improvement after overcoming a serious injury or medical condition or after a previous slump in the career

In [30]:
# MLS Comeback Player of the Year Award
url_cpoty = "https://en.wikipedia.org/wiki/MLS_Comeback_Player_of_the_Year_Award"
html_cpoty = pd.read_html(url_cpoty)

html_cpoty[0].head(20)

    Season             Player                    Team
0     2000         Tony Meola     Kansas City Wizards
1     2001         Troy Dayak    San Jose Earthquakes
2     2002        Chris Klein     Kansas City Wizards
3     2003        Chris Armas            Chicago Fire
4     2004        Brian Ching    San Jose Earthquakes
5     2005    Chris Klein (2)     Kansas City Wizards
6     2006  Richard Mulrooney               FC Dallas
7     2007      Eddie Johnson     Kansas City Wizards
8     2008       Kenny Cooper               FC Dallas
9     2009      Zach Thornton              Chivas USA
10    2010       Bobby Convey    San Jose Earthquakes
11    2011      David Beckham      Los Angeles Galaxy
12    2012  Eddie Johnson (2)     Seattle Sounders FC
13    2013       Kevin Alston  New England Revolution
14    2014     Rodney Wallace        Portland Timbers
15    2015          Tim Melia    Sporting Kansas City
16    2016      Chris Pontius      Philadelphia Union
17    2017      Clint Dempsey     Seattle Sounders FC
18    2018       Gyasi Zardes           Columbus Crew
19    2019      Jordan Morris     Seattle Sounders FC

In [31]:
comeback_award = html_cpoty[0]

comeback_award.dtypes

Season     int64
Player    object
Team      object
dtype: object

In [32]:
comeback_award['Player'] = comeback_award['Player'].str.replace(r'\s*\(.*\)', '', regex=True)
comeback_award.head(10)

   Season             Player                  Team
0    2000         Tony Meola   Kansas City Wizards
1    2001         Troy Dayak  San Jose Earthquakes
2    2002        Chris Klein   Kansas City Wizards
3    2003        Chris Armas          Chicago Fire
4    2004        Brian Ching  San Jose Earthquakes
5    2005        Chris Klein   Kansas City Wizards
6    2006  Richard Mulrooney             FC Dallas
7    2007      Eddie Johnson   Kansas City Wizards
8    2008       Kenny Cooper             FC Dallas
9    2009      Zach Thornton            Chivas USA

In [33]:
# Rename 'Season' to 'Year'
comeback_award = comeback_award.rename(columns ={'Season':'Year'})

comeback_award.head()

   Year       Player                  Team
0  2000   Tony Meola   Kansas City Wizards
1  2001   Troy Dayak  San Jose Earthquakes
2  2002  Chris Klein   Kansas City Wizards
3  2003  Chris Armas          Chicago Fire
4  2004  Brian Ching  San Jose Earthquakes

### MLS Defender of the Year Award
Annual MLS award handed out to the top defender in Major League Soccer annually since the league's inception in 1996

In [34]:
# MLS Defender of the Year Award
url_doty = "https://en.wikipedia.org/wiki/MLS_Defender_of_the_Year_Award"
html_doty = pd.read_html(url_doty)

html_doty[0]

     Season  ...                                          Finalists
0      1996  ...                                                NaN
1      1997  ...                                                NaN
2      1998  ...                                                NaN
3      1999  ...                                                NaN
4      2000  ...                                                NaN
5      2001  ...                                                NaN
6      2002  ...                                                NaN
7      2003  ...                                                NaN
8   2004[3]  ...                            Jimmy Conrad Eddie Pope
9   2005[4]  ...                       Danny Califf Tyrone Marshall
10  2006[5]  ...                         Jimmy Conrad Jose Burciaga
11     2007  ...                                                NaN
12  2008[6]  ...                        Jimmy Conrad Bakary Soumare
13     2009  ...                                                NaN
14  2010[7]  ...                         Omar Gonzalez Nat Borchers
15     2011  ...           Jámison Olave Nat Borchers Carlos Valdés
16     2012  ...       Víctor Bernárdez Aurélien Collin Jay DeMerit
17     2013  ...            Matt Besler Omar Gonzalez Jámison Olave
18     2014  ...      Bobby Boswell Omar Gonzalez Michael Parkhurst
19     2015  ...             Kendall Waston Matt Hedges Matt Miazga
20     2016  ...  Jelle Van Damme Axel Sjöberg Walker Zimmerman ...
21     2017  ...  Justin Morrow Kendall Waston Leandro González ...
22     2018  ...  Chad Marshall Michael Parkhurst Leandro Gonzál...
23     2019  ...  Walker Zimmerman Miles Robinson Maxime Chanot ...
24     2020  ...  Mark McKenzie Jonathan Mensah Anton Tinnerholm...
25     2021  ...  Yeimar Gómez Andrade Miles Robinson Andreu Fon...
26     2022  ...                       Kai Wagner Alexander Callens

[27 rows x 4 columns]

In [35]:
defender_award = html_doty[0]

defender_award.dtypes

Season       object
Winner       object
Team         object
Finalists    object
dtype: object

In [36]:
defender_award['Season'] = defender_award['Season'].str.replace(r'\[.*?\]', '', regex=True)
defender_award['Winner'] = defender_award['Winner'].str.replace(r'\s*\(.*\)', '', regex=True)

# Rename Finalists columns
#df.rename(columns={"A": "a", "B": "c"})
defender_award = defender_award.rename(columns ={"Finalists": "Defender Award Other Finalists"})

defender_award.head()

  Season        Winner                 Team Defender Award Other Finalists
0   1996    John Doyle       San Jose Clash                            NaN
1   1997    Eddie Pope          D.C. United                            NaN
2   1998   Luboš Kubík         Chicago Fire                            NaN
3   1999  Robin Fraser   Los Angeles Galaxy                            NaN
4   2000  Peter Vermes  Kansas City Wizards                            NaN

In [37]:
# Rename columns as needed
defender_award = defender_award.rename(columns ={'Season': 'Year', 'Winner': 'Player'})
defender_award.head()

   Year        Player                 Team Defender Award Other Finalists
0  1996    John Doyle       San Jose Clash                            NaN
1  1997    Eddie Pope          D.C. United                            NaN
2  1998   Luboš Kubík         Chicago Fire                            NaN
3  1999  Robin Fraser   Los Angeles Galaxy                            NaN
4  2000  Peter Vermes  Kansas City Wizards                            NaN

In [38]:
defender_award.dtypes

Year                              object
Player                            object
Team                              object
Defender Award Other Finalists    object
dtype: object

### MLS Goalkeeper of the Year Award
Annual MLS award established in 1996. It is voted on by media, MLS players and club management based on regular-season performance

In [39]:
# MLS Goalkeeper of the Year Award
url_GKoty = "https://en.wikipedia.org/wiki/MLS_Goalkeeper_of_the_Year_Award"
html_GKoty = pd.read_html(url_GKoty)

html_GKoty[0].head(30)

      Season                Winner  ...             Fourth           Fifth
0       1996             Mark Dodd  ...     Mark Dougherty             NaN
1       1997          Brad Friedel  ...        Mike Ammann             NaN
2       1998         Zach Thornton  ...          Ian Feuer             NaN
3       1999         Kevin Hartman  ...       Tom Presthus             NaN
4       2000            Tony Meola  ...      Zach Thornton             NaN
5       2001            Tim Howard  ...       Tom Presthus             NaN
6       2002            Joe Cannon  ...      Kevin Hartman             NaN
7       2003            Pat Onstad  ...         Adin Brown             NaN
8       2004        Joe Cannon (2)  ...         Pat Onstad             NaN
9       2005        Pat Onstad (2)  ...        Bo Oshoniyi             NaN
10      2006          Troy Perkins  ...      Preston Burpo      Dario Sala
11      2007            Brad Guzan  ...         Joe Cannon    Troy Perkins
12      2008             Jon Busch  ...        Greg Sutton  William Hesmer
13      2009     Zach Thornton (2)  ...          Matt Reis       Jon Busch
14      2010      Donovan Ricketts  ...         Joe Cannon   Zach Thornton
15   2011[3]          Kasey Keller  ...       Nick Rimando   Josh Saunders
16   2012[4]         Jimmy Nielsen  ...  Michael Gspurning    Nick Rimando
17   2013[1]  Donovan Ricketts (2)  ...        Luis Robles      Tally Hall
18   2014[5]            Bill Hamid  ...       Jaime Penedo      Joe Bendik
19   2015[6]           Luis Robles  ...         Bill Hamid       Evan Bush
20   2016[7]           Andre Blake  ...         Bill Hamid   David Bingham
21   2017[8]             Tim Melia  ...          Alex Bono    Sean Johnson
22   2018[9]          Zack Steffen  ...          Tim Melia      Brad Guzan
23  2019[10]          Vito Mannone  ...         Brad Guzan     Matt Turner
24  2020[11]       Andre Blake (2)  ...      Pedro Gallese     Stefan Frei
25  2021[12]           Matt Turner  ...  William Yarbrough  Maxime Crépeau
26   2022[2]       Andre Blake (3)  ...    Roman Celentano     Brad Stuver

[27 rows x 7 columns]

In [40]:
gk_award = html_GKoty[0]

gk_award.dtypes

Season    object
Winner    object
Club      object
Second    object
Third     object
Fourth    object
Fifth     object
dtype: object

In [41]:
gk_award['Season'] = gk_award['Season'].str.replace(r'\[.*?\]', '', regex=True)
gk_award['Winner'] = gk_award['Winner'].str.replace(r'\s*\(.*\)', '', regex=True)

gk_award.head()

  Season         Winner  ...          Fourth Fifth
0   1996      Mark Dodd  ...  Mark Dougherty   NaN
1   1997   Brad Friedel  ...     Mike Ammann   NaN
2   1998  Zach Thornton  ...       Ian Feuer   NaN
3   1999  Kevin Hartman  ...    Tom Presthus   NaN
4   2000     Tony Meola  ...   Zach Thornton   NaN

[5 rows x 7 columns]

In [42]:
# Drop club before creating individual rows
gk_award = gk_award.drop(columns =['Club'])

In [43]:
# Generate individual rows for each player - function to be used on gk_award
columns_to_split = ['Winner', 'Second', 'Third', 'Fourth', 'Fifth']
new_rows = []

for index,row in gk_award.iterrows():
    year = row['Season']
    
    for column in columns_to_split:
        place = column
        player = row[column]
        
        if place == 'Winner':
            place = 1
        elif place == 'Second':
            place = 2
        elif place == 'Third':
            place = 3
        elif place == 'Fourth':
            place = 4
        elif place == 'Fifth':
            place = 5
        
        if pd.notna(player):
            new_row = {
                'Year': year,
                'Player': player,
                'GK of the Year Rank': place
            }
            new_rows.append(new_row)
            
    new_df = pd.DataFrame(new_rows)

gk_award = new_df
gk_award.head()

   Year          Player  GK of the Year Rank
0  1996       Mark Dodd                    1
1  1996    Jorge Campos                    2
2  1996  Dave Salzwedel                    3
3  1996  Mark Dougherty                    4
4  1997    Brad Friedel                    1

In [44]:
gk_award.dtypes

Year                   object
Player                 object
GK of the Year Rank     int64
dtype: object

### MLS Goal of the Year Award
Handed out annually since its inception in 1996 to a player in Major League Soccer (MLS) whose goal is selected in an on-line fan vote including the season's Goal of the Week Award winner

In [45]:
# MLS Goal of the Year Award
url_goty = "https://en.wikipedia.org/wiki/MLS_Goal_of_the_Year_Award"
html_goty = pd.read_html(url_goty)

html_goty[0]

    Season                 Scorer  ...                Date  Ref.
0     1996           Eric Wynalda  ...       April 6, 1996   NaN
1     1997       Marco Etcheverry  ...     August 27, 1997   NaN
2     1998          Brian McBride  ...        July 9, 1998   NaN
3     1999   Marco Etcheverry (2)  ...        May 22, 1999   NaN
4     2000         Marcelo Balboa  ...      April 22, 2000   NaN
5     2001           Clint Mathis  ...      April 28, 2001   NaN
6     2002            Carlos Ruiz  ...       July 27, 2002   NaN
7     2003           Damani Ralph  ...     August 13, 2003   NaN
8     2004      Dwayne De Rosario  ...      August 7, 2004   NaN
9     2005  Dwayne De Rosario (2)  ...    October 15, 2005   NaN
10    2006            Brian Ching  ...  September 30, 2006   NaN
11    2007      Cuauhtémoc Blanco  ...     August 18, 2007   NaN
12    2008           Will Johnson  ...    October 18, 2008   NaN
13    2009         Landon Donovan  ...      August 8, 2009   NaN
14    2010            Marco Pappa  ...      April 10, 2010   [1]
15    2011       Darlington Nagbe  ...        July 2, 2011   [2]
16    2012          Patrick Ianni  ...       June 20, 2012   [3]
17    2013        Camilo Sanvezzo  ...     October 6, 2013   [4]
18    2014        Obafemi Martins  ...        May 17, 2014   [5]
19    2015       Krisztián Németh  ...     October 3, 2015   [6]
20    2016         Shkëlzen Gashi  ...  September 24, 2016   [7]
21    2017        Héctor Villalba  ...       July 21, 2017   [8]
22    2018     Zlatan Ibrahimović  ...      March 31, 2018   [9]
23    2019         Josef Martínez  ...  September 18, 2019  [10]
24    2020   Darlington Nagbe (2)  ...     August 20, 2020  [11]
25    2021            Rubio Rubin  ...         May 7, 2021  [12]
26    2022     Josef Martínez (2)  ...     October 1, 2022  [13]

[27 rows x 8 columns]

In [46]:
goal_award = html_goty[0]

goal_award.dtypes

Season          int64
Scorer         object
Nationality    object
For            object
Opponent       object
Stadium        object
Date           object
Ref.           object
dtype: object

In [47]:
# df.drop(columns =['C', 'D'])
goal_award = goal_award.drop(columns = ['Nationality', 'Opponent', 'Stadium', 'Date','Ref.'])
goal_award['Scorer'] = goal_award['Scorer'].str.replace(r'\s*\(.*\)', '', regex=True)

goal_award.head()

   Season            Scorer              For
0    1996      Eric Wynalda   San Jose Clash
1    1997  Marco Etcheverry      D.C. United
2    1998     Brian McBride    Columbus Crew
3    1999  Marco Etcheverry      D.C. United
4    2000    Marcelo Balboa  Colorado Rapids

In [48]:
# Update table to rename columns and drop irrelevant information: 'Season', 'Player', 'Team' renamed
#df.rename(columns={"A": "a", "B": "c"})

goal_award = goal_award.rename(columns ={"Scorer": "Player", "For": "Team", "Season": "Year"})
goal_award.head()

   Year            Player             Team
0  1996      Eric Wynalda   San Jose Clash
1  1997  Marco Etcheverry      D.C. United
2  1998     Brian McBride    Columbus Crew
3  1999  Marco Etcheverry      D.C. United
4  2000    Marcelo Balboa  Colorado Rapids

### MLS Golden Boot
Awarded since the 2005 season to Major League Soccer's regular–season leading scorer. The award replaced the MLS Scoring Champion Award that was awarded since the league's inception in 1996.

In [49]:
# MLS Golden Boot
url_gb = "https://en.wikipedia.org/wiki/MLS_Golden_Boot"
html_gb = pd.read_html(url_gb)

html_gb[0].head(20)

   Season                  Player(s)  ... Assists (1 point) Points
0    1996               Roy Lassiter  ...                 4     58
1    1997                      Preki  ...                17     41
2    1998                 Stern John  ...                 5     57
3    1999                Jason Kreis  ...                15     51
4    2000             Mamadou Diallo  ...                 4     56
5    2001         Alex Pineda Chacón  ...                 9     47
6    2002            Taylor Twellman  ...                 6     52
7    2003                  Preki (2)  ...                17     41
8    2004  Amado Guevara  Pat Noonan  ...              10 8     30

[9 rows x 6 columns]

In [50]:
former_boot = html_gb[0]

In [51]:
# former_booter: split multiplayer rows accordingly
# update function to include space
former_boot['Player(s)'] = former_boot['Player(s)'].str.replace(r'\s*\(.*\)', '', regex=True)
former_boot['Player(s)'] = former_boot['Player(s)'].str.replace('  ', '|', regex=True)
former_boot

   Season                 Player(s)  ... Assists (1 point) Points
0    1996              Roy Lassiter  ...                 4     58
1    1997                     Preki  ...                17     41
2    1998                Stern John  ...                 5     57
3    1999               Jason Kreis  ...                15     51
4    2000            Mamadou Diallo  ...                 4     56
5    2001        Alex Pineda Chacón  ...                 9     47
6    2002           Taylor Twellman  ...                 6     52
7    2003                     Preki  ...                17     41
8    2004  Amado Guevara|Pat Noonan  ...              10 8     30

[9 rows x 6 columns]

In [52]:
# Split rows
new_rows = []
for index, row in former_boot.iterrows():
    year = row['Season']
    points = row['Points']
    
    players = row['Player(s)'].split('|')
    
    for player in players:
        new_row = {
            'Year': year,
            'Player': player,
            'Points': points
        }
        new_rows.append(new_row)
new_df = pd.DataFrame(new_rows)
        
former_boot = new_df
former_boot

   Year              Player  Points
0  1996        Roy Lassiter      58
1  1997               Preki      41
2  1998          Stern John      57
3  1999         Jason Kreis      51
4  2000      Mamadou Diallo      56
5  2001  Alex Pineda Chacón      47
6  2002     Taylor Twellman      52
7  2003               Preki      41
8  2004       Amado Guevara      30
9  2004          Pat Noonan      30

In [53]:
html_gb[1].head()

   Season               Player                    Club  Goals  Games  Rate
0    2005  Taylor Twellman (2)  New England Revolution     17     25  0.68
1    2006      Jeff Cunningham          Real Salt Lake     16     31  0.52
2    2007       Luciano Emilio             D.C. United     20     29  0.69
3    2008       Landon Donovan      Los Angeles Galaxy     20     25  0.80
4    2009  Jeff Cunningham (2)               FC Dallas     17     28  0.61

In [54]:
boot_award = html_gb[1]


boot_award.dtypes

Season      int64
Player     object
Club       object
Goals       int64
Games       int64
Rate      float64
dtype: object

In [55]:
# Strip references from code
boot_award['Player'] = boot_award['Player'].str.replace(r'\s*\(.*\)', '', regex=True)

# Rename Season Column
boot_award = boot_award.rename(columns ={'Season':'Year'})

boot_award.head()

   Year           Player                    Club  Goals  Games  Rate
0  2005  Taylor Twellman  New England Revolution     17     25  0.68
1  2006  Jeff Cunningham          Real Salt Lake     16     31  0.52
2  2007   Luciano Emilio             D.C. United     20     29  0.69
3  2008   Landon Donovan      Los Angeles Galaxy     20     25  0.80
4  2009  Jeff Cunningham               FC Dallas     17     28  0.61

In [56]:
# merge 
boot_award = pd.concat([former_boot, boot_award], axis=0).reset_index(drop=True)

In [57]:
# Boot Awards for larger awards file
boot_award = boot_award.drop(columns =['Club', 'Goals','Games', 'Rate', 'Points'])

boot_award.head(15)

    Year              Player
0   1996        Roy Lassiter
1   1997               Preki
2   1998          Stern John
3   1999         Jason Kreis
4   2000      Mamadou Diallo
5   2001  Alex Pineda Chacón
6   2002     Taylor Twellman
7   2003               Preki
8   2004       Amado Guevara
9   2004          Pat Noonan
10  2005     Taylor Twellman
11  2006     Jeff Cunningham
12  2007      Luciano Emilio
13  2008      Landon Donovan
14  2009     Jeff Cunningham

### MLS Player of the Month
Monthly soccer award given to players in Major League Soccer. The honor is given to the player deemed to have had the best cumulative performance in each month by a panel of journalists from the North American Soccer Reporters organization.[1] The award was formerly voted on by the Professional Soccer Reporters Association

In [58]:
# MLS Player of the Month
url_potm = "https://en.wikipedia.org/wiki/MLS_Player_of_the_Month"
html_potm = pd.read_html(url_potm)

# 2023 Awards 
html_potm[0].head()

              Month             Player  ...           Stats Ref.
0  February & March      Thiago Almada  ...  4 GP, 4 G, 4 A  [3]
1             April  Cristian Espinoza  ...  5 GP, 5 G, 1 A  [4]
2               May       Hany Mukhtar  ...  5 GP, 6 G, 2 A  [5]
3              June        Alan Pulido  ...  5 GP, 6 G, 1 A  [6]
4              July     Luciano Acosta  ...  3 GP, 3 G, 4 A  [7]

[5 rows x 5 columns]

In [59]:
#mthlyplayer_award = html_potm[0]

#mthlyplayer_award.dtypes

In [60]:
# team_names = pd.concat([former_teams, team_names], axis=0).reset_index(drop=True)
#var_year = 2023
#mthlyplayer_award['Year'] = var_year

#mthlyplayer_award.head()

In [61]:
# 2022 Awards
html_potm[1].head()

              Month             Player           Club           Stats  Ref.
0  February & March    Lucas Zelarayán  Columbus Crew  4 GP, 4 G, 1 A  [10]
1             April  Sebastián Driussi      Austin FC  5 GP, 4 G, 1 A  [11]
2               May       Paul Arriola      FC Dallas       5 GP, 6 G  [12]
3              June     Luciano Acosta  FC Cincinnati  3 GP, 1 G, 3 A  [13]
4              July  Sebastián Driussi      Austin FC  6 GP, 5 G, 3 A  [14]

In [62]:
test = html_potm[10].head()

In [63]:
type(test)

pandas.core.frame.DataFrame

In [64]:
for col in test.columns:
    print(col)

('Month', 'Month')
('Unnamed: 1_level_0', 'Player')
('Unnamed: 2_level_0', 'Club')
('Unnamed: 3_level_0', 'Link')

In [65]:
print(test.columns.nlevels)

2

In [66]:
if test.columns.nlevels == 2:
    # Your code to drop the second level here
    test.columns = test.columns.droplevel(level=0)
    
for col in test.columns: 
    print(col)

Month
Player
Club
Link

In [67]:
# Create a for loop to iterate through the various tables
# for 2023 - 2005 (from 1 - 18)
# counter = 1
# months_year = html_potm[counter]
# months_year['Year'] = var_year - 1
# mthlyplayer_award = pd.concat([months_year, mthlyplayer_award], axis=0).reset_index(drop=True)
# counter++
# return mthlyplayer_award

from datetime import datetime

var_year = datetime.now().year  # Current year

def process_monthly_award_data(html_potm, var_year):
    mthlyplayer_award = pd.DataFrame()

    for counter in range(1, var_year - 2005 + 1):  # Loop from 1 to 18 (2005 to 2022)        
        months_year = html_potm[counter]
        
        if months_year.columns.nlevels == 2:
            # Your code to drop the second level here
            months_year.columns = months_year.columns.droplevel(level=0)
        
        months_year['Year'] = var_year - counter
        
        
        mthlyplayer_award = pd.concat([mthlyplayer_award, months_year], ignore_index=True).reset_index(drop=True)
        
    return mthlyplayer_award

# Call the function with your actual data and current year
mthlyplayer_award = process_monthly_award_data(html_potm, var_year)


mthlyplayer_award.head(20)

                  Month                Player  ...  Year Link
0      February & March       Lucas Zelarayán  ...  2022  NaN
1                 April     Sebastián Driussi  ...  2022  NaN
2                   May          Paul Arriola  ...  2022  NaN
3                  June        Luciano Acosta  ...  2022  NaN
4                  July     Sebastián Driussi  ...  2022  NaN
5                August          Hany Mukhtar  ...  2022  NaN
6   September & October               Brenner  ...  2022  NaN
7           April & May      Javier Hernández  ...  2021  NaN
8                  June            Carles Gil  ...  2021  NaN
9                  July           Gustavo Bou  ...  2021  NaN
10               August  Valentín Castellanos  ...  2021  NaN
11            September         Eduardo López  ...  2021  NaN
12               August            Daryl Dike  ...  2020  NaN
13            September     Alejandro Pozuelo  ...  2020  NaN
14   October & November  Valentín Castellanos  ...  2020  NaN
15                March           Carlos Vela  ...  2019  NaN
16                April           Carlos Vela  ...  2019  NaN
17                  May     Chris Wondolowski  ...  2019  NaN
18                 June   Maximiliano Moralez  ...  2019  NaN
19                 July        Josef Martínez  ...  2019  NaN

[20 rows x 7 columns]

In [68]:
# Drop 'Ref.' column and rename 'Stats' column to know its a 
mthlyplayer_award = mthlyplayer_award.drop(columns =['Club', 'Stats', 'Ref.', 'Link'])

mthlyplayer_award.head()

              Month             Player  Year
0  February & March    Lucas Zelarayán  2022
1             April  Sebastián Driussi  2022
2               May       Paul Arriola  2022
3              June     Luciano Acosta  2022
4              July  Sebastián Driussi  2022

In [69]:
# Initialize "No of Months" column with 1
mthlyplayer_award["No of Months"] = 1

# Split "Month" column and create new rows
mthlyplayer_award = mthlyplayer_award.assign(Month=mthlyplayer_award['Month'].str.split(' & ')).explode('Month')

# Group by "Player" and "Year" and calculate the sum of "No of Months"
mthlyplayer_award = mthlyplayer_award.groupby(["Player", "Year"])["No of Months"].sum().reset_index()

# Display the updated DataFrame
mthlyplayer_award.head()

              Player  Year  No of Months
0     Adama Diomande  2018             1
1  Alejandro Pozuelo  2020             1
2      Amado Guevara  2006             1
3    Benny Feilhaber  2014             1
4    Benny Feilhaber  2015             1

### Landon Donovan MVP Award
An annual award for Major League Soccer players. It is voted on by media, MLS players, and club management and is given to the player deemed the most valuable player in the league each season.

In [70]:
# Landon Donovan MVP Award
url_LDmvp = "https://en.wikipedia.org/wiki/Landon_Donovan_MVP_Award"
html_LDmvp = pd.read_html(url_LDmvp)

html_LDmvp[0].head()

   Season  ...                      Other Finalists
0    1996  ...                  Roy Lassiter, Preki
1    1997  ...  Marco Etcheverry, Carlos Valderrama
2    1998  ...              Cobi Jones, Peter Nowak
3    1999  ...       Marco Etcheverry, Jaime Moreno
4    2000  ...         Mamadou Diallo, Clint Mathis

[5 rows x 4 columns]

In [71]:
landonMVP_award = html_LDmvp[0]

landonMVP_award.dtypes

Season              int64
Player             object
Club               object
Other Finalists    object
dtype: object

In [72]:
landonMVP_award['Player'] = landonMVP_award['Player'].str.replace(r'\s*\(.*\)', '', regex=True)
landonMVP_award['Player'] = landonMVP_award['Player'].str.replace(r'\[.*?\]', '', regex=True)
landonMVP_award['Landon Donovan MVP Winner'] = 1

landonMVP_award.head()

   Season  ... Landon Donovan MVP Winner
0    1996  ...                         1
1    1997  ...                         1
2    1998  ...                         1
3    1999  ...                         1
4    2000  ...                         1

[5 rows x 5 columns]

In [73]:
# Split up 'Other Finalists' column and create new rows for each player
# Look into first row with 'Preki' - ???
# Remodel function to create new_rows and concat to bestXI_award df
# Latest bestXI_award: 'Year', 'Player', 'Team', and 'Position'

new_rows = []
for index, row in landonMVP_award.iterrows():
    year = row['Season']
    
    other_finalists = row['Other Finalists'].split(', ')
    
    for finalist in other_finalists:
        new_row = {
            'Year': year,
            'Player': finalist,
            'Landon Donovan MVP Winner': 1
        }
        new_rows.append(new_row)
new_df = pd.DataFrame(new_rows)

# Clean up original dataframe to align with same naming conventions and columns
landonMVP_award = landonMVP_award[['Season', 'Player']]
landonMVP_award = landonMVP_award.rename(columns={'Season': 'Year'})
        
result = pd.concat([landonMVP_award, new_df], ignore_index=True)
result.head(30)

    Year                      Player  Landon Donovan MVP Winner
0   1996           Carlos Valderrama                        NaN
1   1997                       Preki                        NaN
2   1998            Marco Etcheverry                        NaN
3   1999                 Jason Kreis                        NaN
4   2000                  Tony Meola                        NaN
5   2001          Alex Pineda Chacón                        NaN
6   2002                 Carlos Ruíz                        NaN
7   2003                       Preki                        NaN
8   2004               Amado Guevara                        NaN
9   2005             Taylor Twellman                        NaN
10  2006             Christian Gómez                        NaN
11  2007              Luciano Emilio                        NaN
12  2008  Guillermo Barros Schelotto                        NaN
13  2009              Landon Donovan                        NaN
14  2010              David Ferreira                        NaN
15  2011           Dwayne De Rosario                        NaN
16  2012           Chris Wondolowski                        NaN
17  2013                  Mike Magee                        NaN
18  2014                Robbie Keane                        NaN
19  2015          Sebastian Giovinco                        NaN
20  2016                 David Villa                        NaN
21  2017                Diego Valeri                        NaN
22  2018              Josef Martínez                        NaN
23  2019                 Carlos Vela                        NaN
24  2020           Alejandro Pozuelo                        NaN
25  2021                  Carles Gil                        NaN
26  2022                Hany Mukhtar                        NaN
27  1996                Roy Lassiter                        1.0
28  1996                       Preki                        1.0
29  1997            Marco Etcheverry                        1.0

In [74]:
landonMVP_award.dtypes

Year       int64
Player    object
dtype: object

### MLS All-Star Game MVP
Annual soccer game held by Major League Soccer featuring selected players from the league against an international club or selected players from another league. The MLS All-Stars hold a 9–8 record in the competition, which generally marks the season's midpoint. Players are awarded roster spots through a combination of fan voting and selections by the appointed manager and league commissioner. NOTE: MVP of the game does not need to be from the MLS

In [75]:
# MLS All-Star Game MVP
url_ASmvp = "https://en.wikipedia.org/wiki/MLS_All-Star_Game"
html_ASmvp = pd.read_html(url_ASmvp)

html_ASmvp[33].head(30)

     Ed.  ...                               MLS club
0   1996  ...                       Tampa Bay Mutiny
1   1997  ...                       Tampa Bay Mutiny
2   1998  ...                          Columbus Crew
3   1999  ...                    Kansas City Wizards
4   2000  ...                       Tampa Bay Mutiny
5   2001  ...                   San Jose Earthquakes
6   2002  ...                            D.C. United
7   2003  ...                              LA Galaxy
8   2004  ...                       NY/NJ Metrostars
9   2005  ...                 New England Revolution
10  2006  ...                         Houston Dynamo
11  2007  ...                     New York Red Bulls
12  2008  ...                           Chicago Fire
13  2009  ...                                      —
14  2010  ...                                      —
15  2011  ...                                      —
16  2012  ...                            D.C. United
17  2013  ...                                      —
18  2014  ...                              LA Galaxy
19  2015  ...                           Orlando City
20  2016  ...                                      —
21  2017  ...                                      —
22  2018  ...                      Atlanta United FC
23  2019  ...                                      —
24  2020  ...  Canceled due to COVID-19 pandemic[14]
25  2021  ...                 New England Revolution
26  2022  ...                    Minnesota United FC
27  2023  ...                                      —

[28 rows x 6 columns]

In [76]:
allstarMVP_award = html_ASmvp[33]

allstarMVP_award.dtypes

Ed.             int64
Winner         object
Nationality    object
Position       object
Team           object
MLS club       object
dtype: object

In [77]:
# Remove non-MLS players, where Team != 'MLS All-Stars'
allstarMVP_award = allstarMVP_award[allstarMVP_award['MLS club'] != '—']

# df.drop(df[df['Fee'] >= 24000].index, inplace = True)

allstarMVP_award = allstarMVP_award[allstarMVP_award['MLS club'] != 'Canceled due to COVID-19 pandemic[14]']


allstarMVP_award.head(30)

     Ed.               Winner  ...           Team                MLS club
0   1996    Carlos Valderrama  ...       MLS East        Tampa Bay Mutiny
1   1997    Carlos Valderrama  ...       MLS East        Tampa Bay Mutiny
2   1998        Brian McBride  ...        MLS USA           Columbus Crew
3   1999                Preki  ...       MLS West     Kansas City Wizards
4   2000       Mamadou Diallo  ...       MLS East        Tampa Bay Mutiny
5   2001       Landon Donovan  ...       MLS West    San Jose Earthquakes
6   2002     Marco Etcheverry  ...  MLS All-Stars             D.C. United
7   2003          Carlos Ruiz  ...  MLS All-Stars               LA Galaxy
8   2004        Amado Guevara  ...       MLS East        NY/NJ Metrostars
9   2005      Taylor Twellman  ...  MLS All-Stars  New England Revolution
10  2006    Dwayne De Rosario  ...  MLS All-Stars          Houston Dynamo
11  2007     Juan Pablo Ángel  ...        MLS USA      New York Red Bulls
12  2008    Cuauhtémoc Blanco  ...  MLS All-Stars            Chicago Fire
16  2012        Chris Pontius  ...  MLS All-Stars             D.C. United
18  2014       Landon Donovan  ...  MLS All-Stars               LA Galaxy
19  2015                 Kaká  ...  MLS All-Stars            Orlando City
22  2018       Josef Martínez  ...  MLS All-Stars       Atlanta United FC
25  2021      Matt Turner[15]  ...  MLS All-Stars  New England Revolution
26  2022  Dayne St. Clair[16]  ...  MLS All-Stars     Minnesota United FC

[19 rows x 6 columns]

In [78]:
# Rename columns, drop those that aren't needed
allstarMVP_award = allstarMVP_award.drop(columns =['Nationality', 'Position', 'Team'])
allstarMVP_award = allstarMVP_award.rename(columns ={'Ed.': 'Year', 'Winner': 'Player', 'MLS club': 'Team'})

allstarMVP_award.head()

   Year             Player                 Team
0  1996  Carlos Valderrama     Tampa Bay Mutiny
1  1997  Carlos Valderrama     Tampa Bay Mutiny
2  1998      Brian McBride        Columbus Crew
3  1999              Preki  Kansas City Wizards
4  2000     Mamadou Diallo     Tampa Bay Mutiny

### MLS Cup MVP
The MLS Cup is the annual championship game of Major League Soccer (MLS) and the culmination of the MLS Cup Playoffs. The game is held in November or December and pits the winner of the Eastern Conference Final against the winner of the Western Conference Final. The MLS Cup winner is awarded the title of league champion.

Following each championship, a player on the winning club is awarded with the title of being the Most Valuable Player (MVP). Usually, but not necessarily, the winner of the award is the player who scores the game-winning goal, or sets up the game-winning goal

In [79]:
# MLS Cup MVP
url_Cmvp = "https://en.wikipedia.org/wiki/MLS_Cup"
html_Cmvp = pd.read_html(url_Cmvp)

html_Cmvp[1].head()

   Season         Date  ... Attendance U.S. television
0    1996   October 20  ...      34643             ABC
1    1997   October 26  ...      57431             ABC
2    1998   October 25  ...      51350             ABC
3    1999  November 21  ...      44910             ABC
4    2000   October 15  ...      39159             ABC

[5 rows x 8 columns]

In [80]:
cupMVP_award = html_Cmvp[7]

cupMVP_award.dtypes

Year         int64
Winner      object
Position    object
Club        object
dtype: object

In [81]:
cupMVP_award.head()

   Year            Winner    Position                 Club
0  1996  Marco Etcheverry  Midfielder          D.C. United
1  1997      Jaime Moreno     Forward          D.C. United
2  1998       Peter Nowak  Midfielder         Chicago Fire
3  1999         Ben Olsen  Midfielder          D.C. United
4  2000        Tony Meola  Goalkeeper  Kansas City Wizards

In [82]:
cupMVP_award.dtypes

Year         int64
Winner      object
Position    object
Club        object
dtype: object

In [83]:
html_Cmvp[3].head()

   Apps  Years  ...  Win %            Years of appearance (in MLS Cup Finals)
0     9     27  ...  0.556  1996, 1999, 2001, 2002, 2005, 2009, 2011, 2012...
1     5     27  ...  0.800                       1996, 1997, 1998, 1999, 2004
2     4     17  ...  0.500                             2006, 2007, 2011, 2012
3     4     14  ...  0.500                             2016, 2017, 2019, 2020
4     3     27  ...  0.667                                   2000, 2004, 2013

[5 rows x 7 columns]

In [84]:
cup_teams = html_Cmvp[3]

cup_teams.dtypes

Apps                                         int64
Years                                        int64
Club                                        object
Wins                                         int64
Losses                                       int64
Win %                                      float64
Years of appearance (in MLS Cup Finals)     object
dtype: object

### MLS Newcomer of the Year
Awarded by Major League Soccer to a player who has professional experience in another league and has an outstanding season in his first season of play in MLS

In [85]:
# MLS Newcomer of the Year
url_noty = "https://en.wikipedia.org/wiki/MLS_Newcomer_of_the_Year_Award"
html_noty = pd.read_html(url_noty)

html_noty[0].head(20)

    Season           Player[3]                 Club[3]
0     2007      Luciano Emilio             D.C. United
1     2008     Darren Huckerby    San Jose Earthquakes
2     2009       Fredy Montero     Seattle Sounders FC
3     2010      Álvaro Saborío          Real Salt Lake
4     2011       Mauro Rosales     Seattle Sounders FC
5     2012    Federico Higuaín        Columbus Crew SC
6     2013        Diego Valeri        Portland Timbers
7     2014       Pedro Morales  Vancouver Whitecaps FC
8     2015  Sebastian Giovinco              Toronto FC
9     2016     Nicolás Lodeiro     Seattle Sounders FC
10    2017      Miguel Almirón       Atlanta United FC
11    2018  Zlatan Ibrahimović               LA Galaxy
12    2019          Carles Gil  New England Revolution
13    2020     Lucas Zelarayán        Columbus Crew SC
14    2021     Cristian Arango          Los Angeles FC
15    2022       Thiago Almada       Atlanta United FC

In [86]:
newcomer_award = html_noty[0]

In [87]:
# student_df_1.rename(columns={"id": "ID"}, inplace=True)
newcomer_award.rename(
    columns ={"Season": "Year", "Player[3]": "Player", "Club[3]": "Team"}, 
    inplace=True
)

newcomer_award.head()

   Year           Player                  Team
0  2007   Luciano Emilio           D.C. United
1  2008  Darren Huckerby  San Jose Earthquakes
2  2009    Fredy Montero   Seattle Sounders FC
3  2010   Álvaro Saborío        Real Salt Lake
4  2011    Mauro Rosales   Seattle Sounders FC

In [88]:
newcomer_award.dtypes

Year       int64
Player    object
Team      object
dtype: object

### MLS Young Player of the Year Award
Formerly known as the Rookie of the Year Award from 1996 to 2019 is an annual award given to the top player in Major League Soccer under the age of 22

In [89]:
# MLS Young Player of the Year Award
url_ypoty = "https://en.wikipedia.org/wiki/MLS_Young_Player_of_the_Year_Award"
html_ypoty = pd.read_html(url_ypoty)

html_ypoty[0].head()

   Season            Player  ...               Draft Class                College
0    1996     Steve Ralston  ...    1996 MLS College Draft  Florida International
1    1997      Mike Duhaney  ...  1996 MLS Inaugural Draft                   UNLV
2    1998         Ben Olsen  ...                Project-40               Virginia
3    1999         Jay Heaps  ...    1999 MLS College Draft                   Duke
4    2000  Carlos Bocanegra  ...       2000 MLS SuperDraft                   UCLA

[5 rows x 7 columns]

In [90]:
youngplayer_award = html_ypoty[0]

youngplayer_award.dtypes

Season           int64
Player          object
Position        object
Team            object
Draft Pick     float64
Draft Class     object
College         object
dtype: object

In [91]:
html_ypoty[1].head()

   Season          Player Position            Team  Age
0    2020     Diego Rossi  Forward  Los Angeles FC   22
1    2021    Ricardo Pepi  Forward       FC Dallas   18
2    2022  Jesús Ferreira  Forward       FC Dallas   21

In [92]:
yp2020_onw = html_ypoty[1]

yp2020_onw.dtypes

Season       int64
Player      object
Position    object
Team        object
Age          int64
dtype: object

In [93]:
# team_names = pd.concat([former_teams, team_names], axis=0).reset_index(drop=True)

youngplayer_award = pd.concat([youngplayer_award, yp2020_onw], axis=0).reset_index(drop=True)
youngplayer_award.head(40)

    Season              Player  ...                   College   Age
0     1996       Steve Ralston  ...     Florida International   NaN
1     1997        Mike Duhaney  ...                      UNLV   NaN
2     1998           Ben Olsen  ...                  Virginia   NaN
3     1999           Jay Heaps  ...                      Duke   NaN
4     2000    Carlos Bocanegra  ...                      UCLA   NaN
5     2001       Rodrigo Faria  ...         Concordia College   NaN
6     2002        Kyle Martino  ...                  Virginia   NaN
7     2003        Damani Ralph  ...               Connecticut   NaN
8     2004       Clint Dempsey  ...                    Furman   NaN
9     2005   Michael Parkhurst  ...               Wake Forest   NaN
10    2006  Jonathan Bornstein  ...                      UCLA   NaN
11    2007         Maurice Edu  ...                  Maryland   NaN
12    2008       Sean Franklin  ...      Cal State Northridge   NaN
13    2009       Omar Gonzalez  ...                  Maryland   NaN
14    2010          Andy Najar  ...                       NaN   NaN
15    2011        C. J. Sapong  ...             James Madison   NaN
16    2012        Austin Berry  ...                Louisville   NaN
17    2013       Dillon Powers  ...                Notre Dame   NaN
18    2014      Tesho Akindele  ...  Colorado School of Mines   NaN
19    2015          Cyle Larin  ...               Connecticut   NaN
20    2016       Jordan Morris  ...                  Stanford   NaN
21    2017      Julian Gressel  ...        Providence College   NaN
22    2018         Corey Baird  ...                  Stanford   NaN
23    2019   Andre Shinyashiki  ...                    Denver   NaN
24    2020         Diego Rossi  ...                       NaN  22.0
25    2021        Ricardo Pepi  ...                       NaN  18.0
26    2022      Jesús Ferreira  ...                       NaN  21.0

[27 rows x 8 columns]

In [94]:
# Rename the necessary columns and drop unnecessary columns
youngplayer_award = youngplayer_award.rename(columns ={'Season': 'Year'})

youngplayer_award.head()

   Year            Player  ...                College Age
0  1996     Steve Ralston  ...  Florida International NaN
1  1997      Mike Duhaney  ...                   UNLV NaN
2  1998         Ben Olsen  ...               Virginia NaN
3  1999         Jay Heaps  ...                   Duke NaN
4  2000  Carlos Bocanegra  ...                   UCLA NaN

[5 rows x 8 columns]

## CSV & Data Dictionary Generation

Best MLS Player ESPY Award:

MLS Best XI:

MLS Comeback Player of the Year Award:

MLS Defender of the Year Award:

MLS Goalkeeper of the Year Award:

MLS Goal of the Year Award: 

MLS Golden Boot:

MLS Player of the Month: 

Landon Donovan MVP Award

MLS All-Star Game MVP

MLS Cup MVP

MLS Newcomer of the Year

MLS Young Player of the Year Award

### Player Award Dataframe

In [95]:
def add_found_in_df2_column(df1, df2, on_columns, new_column_name, default_value=0):
    """
    Adds a new column to df1 indicating if a row is found in df2 based on specified columns.

    Args:
        df1 (pd.DataFrame): The first dataframe.
        df2 (pd.DataFrame): The second dataframe.
        on_columns (list): A list of column names to match rows on.
        new_column_name (str): The name of the new column to be added.
        default_value: The value to use in the new column for rows not found in df2.

    Returns:
        pd.DataFrame: The dataframe with the new column indicating row presence in df2.
    """
    # Convert the "Year" column in both dataframes to int
    df1['Year'] = df1['Year'].astype(int)
    df2['Year'] = df2['Year'].astype(int)
    
    # Perform a full outer join on the specified columns
    merged_df = df1.merge(df2, on=on_columns, how='outer', indicator=True)
    
    # Add the new column based on whether the row is found in either dataframe
    merged_df[new_column_name] = (merged_df['_merge'] != 'left_only').astype(int)
    
    # Fill NaN values in the new column with the default value
    merged_df[new_column_name].fillna(default_value, inplace=True)
    
    # Drop the indicator column
    merged_df.drop('_merge', axis=1, inplace=True)
    
    return merged_df

In [96]:
# Create copy of best MLS Espy Award and add a new binary column for award
all_awards = espy_award.copy()

all_awards.head()

   Year          Player Nation       Team  ESPY Winner  ESPY Finalist
0  2006  Landon Donovan    USA  LA Galaxy          1.0              1
1  2007  Landon Donovan    USA  LA Galaxy          1.0              1
2  2008   David Beckham    ENG  LA Galaxy          1.0              1
3  2009  Landon Donovan    USA  LA Galaxy          1.0              1
4  2010  Landon Donovan    USA  LA Galaxy          1.0              1

In [97]:
SELECT * FROM all_awards WHERE Player = 'Landon Donovan'

   Year          Player Nation       Team  ESPY Winner  ESPY Finalist
0  2006  Landon Donovan    USA  LA Galaxy          1.0              1
1  2007  Landon Donovan    USA  LA Galaxy          1.0              1
2  2009  Landon Donovan    USA  LA Galaxy          1.0              1
3  2010  Landon Donovan    USA  LA Galaxy          1.0              1
4  2011  Landon Donovan    USA  LA Galaxy          1.0              1

In [98]:
# Merge in MLS Best XI data
# Specify the columns to match rows on
on_columns = ['Year', 'Player', 'Team']

# Define the name of the new column
new_column_name = 'Best XI'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, bestXI_players, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player Nation  ... ESPY Winner  ESPY Finalist  Best XI
0  2006  Landon Donovan    USA  ...         1.0            1.0        0
1  2007  Landon Donovan    USA  ...         1.0            1.0        0
2  2008   David Beckham    ENG  ...         1.0            1.0        0
3  2009  Landon Donovan    USA  ...         1.0            1.0        0
4  2010  Landon Donovan    USA  ...         1.0            1.0        0
5  2011  Landon Donovan    USA  ...         1.0            1.0        0
6  2012   David Beckham    ENG  ...         1.0            1.0        0
7  2013   Thierry Henry    FRA  ...         1.0            1.0        0
8  2014      Tim Cahill    AUS  ...         1.0            1.0        0
9  2015    Robbie Keane    IRL  ...         1.0            1.0        1

[10 rows x 7 columns]

In [99]:
# Merge Comeback Player of the Year data
# Specify the columns to match rows on
on_columns = ['Year', 'Player', 'Team']

# Define the name of the new column
new_column_name = 'Comeback Player of the Year Winner'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, comeback_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player  ... Best XI Comeback Player of the Year Winner
0  2006  Landon Donovan  ...     0.0                                  0
1  2007  Landon Donovan  ...     0.0                                  0
2  2008   David Beckham  ...     0.0                                  0
3  2009  Landon Donovan  ...     0.0                                  0
4  2010  Landon Donovan  ...     0.0                                  0
5  2011  Landon Donovan  ...     0.0                                  0
6  2012   David Beckham  ...     0.0                                  0
7  2013   Thierry Henry  ...     0.0                                  0
8  2014      Tim Cahill  ...     0.0                                  0
9  2015    Robbie Keane  ...     1.0                                  0

[10 rows x 8 columns]

In [100]:
# Merge Defender of the Year data
# Specify the columns to match rows on
on_columns = ['Year', 'Player', 'Team']

# Define the name of the new column
new_column_name = 'Defender of the Year Winner'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, defender_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year  ... Defender of the Year Winner
0  2006  ...                           0
1  2007  ...                           0
2  2008  ...                           0
3  2009  ...                           0
4  2010  ...                           0
5  2011  ...                           0
6  2012  ...                           0
7  2013  ...                           0
8  2014  ...                           0
9  2015  ...                           0

[10 rows x 10 columns]

In [101]:
# Merge GK of the Year data
# Specify the columns to match rows on
on_columns = ['Year', 'Player']

# Define the name of the new column
new_column_name = 'GK of the Year Finalist'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, gk_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player  ... GK of the Year Rank GK of the Year Finalist
0  2006  Landon Donovan  ...                 NaN                       0
1  2007  Landon Donovan  ...                 NaN                       0
2  2008   David Beckham  ...                 NaN                       0
3  2009  Landon Donovan  ...                 NaN                       0
4  2010  Landon Donovan  ...                 NaN                       0
5  2011  Landon Donovan  ...                 NaN                       0
6  2012   David Beckham  ...                 NaN                       0
7  2013   Thierry Henry  ...                 NaN                       0
8  2014      Tim Cahill  ...                 NaN                       0
9  2015    Robbie Keane  ...                 NaN                       0

[10 rows x 12 columns]

In [102]:
# Merge Goal of the Year data
# Specify the columns to match rows on
on_columns = ['Year', 'Player', 'Team']

# Define the name of the new column
new_column_name = 'Goal of the Year'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, goal_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player  ... GK of the Year Finalist Goal of the Year
0  2006  Landon Donovan  ...                     0.0                0
1  2007  Landon Donovan  ...                     0.0                0
2  2008   David Beckham  ...                     0.0                0
3  2009  Landon Donovan  ...                     0.0                1
4  2010  Landon Donovan  ...                     0.0                0
5  2011  Landon Donovan  ...                     0.0                0
6  2012   David Beckham  ...                     0.0                0
7  2013   Thierry Henry  ...                     0.0                0
8  2014      Tim Cahill  ...                     0.0                0
9  2015    Robbie Keane  ...                     0.0                0

[10 rows x 13 columns]

In [103]:
# Merge MLS Golden Boot data
# Specify the columns to match rows on
on_columns = ['Year', 'Player']

# Define the name of the new column
new_column_name = 'Golden Boot'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, boot_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player  ... Goal of the Year Golden Boot
0  2006  Landon Donovan  ...              0.0           0
1  2007  Landon Donovan  ...              0.0           0
2  2008   David Beckham  ...              0.0           0
3  2009  Landon Donovan  ...              1.0           0
4  2010  Landon Donovan  ...              0.0           0
5  2011  Landon Donovan  ...              0.0           0
6  2012   David Beckham  ...              0.0           0
7  2013   Thierry Henry  ...              0.0           0
8  2014      Tim Cahill  ...              0.0           0
9  2015    Robbie Keane  ...              0.0           0

[10 rows x 14 columns]

In [104]:
# Merge Player of the Month data
# Specify the columns to match rows on
on_columns = ['Year', 'Player']

# Define the name of the new column
new_column_name = 'Player of the Month'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, mthlyplayer_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player Nation  ... Golden Boot  No of Months  Player of the Month
0  2006  Landon Donovan    USA  ...         0.0           NaN                    0
1  2007  Landon Donovan    USA  ...         0.0           NaN                    0
2  2008   David Beckham    ENG  ...         0.0           NaN                    0
3  2009  Landon Donovan    USA  ...         0.0           1.0                    1
4  2010  Landon Donovan    USA  ...         0.0           NaN                    0
5  2011  Landon Donovan    USA  ...         0.0           1.0                    1
6  2012   David Beckham    ENG  ...         0.0           NaN                    0
7  2013   Thierry Henry    FRA  ...         0.0           NaN                    0
8  2014      Tim Cahill    AUS  ...         0.0           NaN                    0
9  2015    Robbie Keane    IRL  ...         0.0           NaN                    0

[10 rows x 16 columns]

In [105]:
# Merge Landon Donovan MVP data
# Specify the columns to match rows on
on_columns = ['Year', 'Player']

# Define the name of the new column
new_column_name = 'Landon Donovan MVP Finalist'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, landonMVP_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player  ... Player of the Month Landon Donovan MVP Finalist
0  2006  Landon Donovan  ...                 0.0                           0
1  2007  Landon Donovan  ...                 0.0                           0
2  2008   David Beckham  ...                 0.0                           0
3  2009  Landon Donovan  ...                 1.0                           1
4  2010  Landon Donovan  ...                 0.0                           0
5  2011  Landon Donovan  ...                 1.0                           0
6  2012   David Beckham  ...                 0.0                           0
7  2013   Thierry Henry  ...                 0.0                           0
8  2014      Tim Cahill  ...                 0.0                           0
9  2015    Robbie Keane  ...                 0.0                           0

[10 rows x 17 columns]

In [106]:
# Merge MLS All-Star Game MVP data
# Specify the columns to match rows on
on_columns = ['Year', 'Player', 'Team']

# Define the name of the new column
new_column_name = 'All-Star Game MVP'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, allstarMVP_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player  ... Landon Donovan MVP Finalist All-Star Game MVP
0  2006  Landon Donovan  ...                         0.0                 0
1  2007  Landon Donovan  ...                         0.0                 0
2  2008   David Beckham  ...                         0.0                 0
3  2009  Landon Donovan  ...                         1.0                 0
4  2010  Landon Donovan  ...                         0.0                 0
5  2011  Landon Donovan  ...                         0.0                 0
6  2012   David Beckham  ...                         0.0                 0
7  2013   Thierry Henry  ...                         0.0                 0
8  2014      Tim Cahill  ...                         0.0                 0
9  2015    Robbie Keane  ...                         0.0                 0

[10 rows x 18 columns]

In [107]:
# Merge MLS Newcomer of the Year data
# Specify the columns to match rows on
on_columns = ['Year', 'Player', 'Team']

# Define the name of the new column
new_column_name = 'Newcomer of the Year'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, newcomer_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player  ... All-Star Game MVP Newcomer of the Year
0  2006  Landon Donovan  ...               0.0                    0
1  2007  Landon Donovan  ...               0.0                    0
2  2008   David Beckham  ...               0.0                    0
3  2009  Landon Donovan  ...               0.0                    0
4  2010  Landon Donovan  ...               0.0                    0
5  2011  Landon Donovan  ...               0.0                    0
6  2012   David Beckham  ...               0.0                    0
7  2013   Thierry Henry  ...               0.0                    0
8  2014      Tim Cahill  ...               0.0                    0
9  2015    Robbie Keane  ...               0.0                    0

[10 rows x 19 columns]

In [108]:
# Merge MLS Young Player of the Year data
on_columns = ['Year', 'Player', 'Team']

# Define the name of the new column
new_column_name = 'Young Player of the Year'

# Call the function to add the new column and include additional columns from df2
# result_df = add_found_in_df2_column(df1, df2, on_columns, new_column_name)
all_awards = add_found_in_df2_column(all_awards, youngplayer_award, on_columns, new_column_name)

# Check latest
all_awards.head(10)

   Year          Player Nation  ... College  Age  Young Player of the Year
0  2006  Landon Donovan    USA  ...     NaN  NaN                         0
1  2007  Landon Donovan    USA  ...     NaN  NaN                         0
2  2008   David Beckham    ENG  ...     NaN  NaN                         0
3  2009  Landon Donovan    USA  ...     NaN  NaN                         0
4  2010  Landon Donovan    USA  ...     NaN  NaN                         0
5  2011  Landon Donovan    USA  ...     NaN  NaN                         0
6  2012   David Beckham    ENG  ...     NaN  NaN                         0
7  2013   Thierry Henry    FRA  ...     NaN  NaN                         0
8  2014      Tim Cahill    AUS  ...     NaN  NaN                         0
9  2015    Robbie Keane    IRL  ...     NaN  NaN                         0

[10 rows x 25 columns]

### Team Award Dataframe

In [109]:
# LATER BUILD...

### Python to CSV & Text Files

In [110]:
# Create a CSV from this information
# all_awards.to_csv('awards.csv')

## Additional Considerations

1. ~~For ESPY awards, creating a method to pull 'Other nominees', where other nominees are a new row include 'Year', 'Player Name', 'Nation', 'Team' and **kwargs on number of additional players~~
2. Cross-reference other 'Finalists' column in dataframe 'defender_award', in lieu of this, included as an additional column to be reviewed with larger player df in repository (renamed 'Defender_award_finalists')
3. MLS Boot award data was merged for simplicity, however, scored differently before 2005
4. Similar scenario for Young Player of the Year award, used to be Rookie of the Year award until 2020; new requirement is under 22 years of age -- might remove considering
5. Season vs. Year:  Assumption that season is synonymous with year unless otherwise stated; some awards handed using a combo of two seasons of play, in those instances, the latter of the two will be used.
6. Use of MLS Young Player of the Year Award to feed into collegiate and academy player talent; what are feeder programs and/or other common paths to MLS (if applicable)?
7. Data frame 'cup_teams' from the MLS Cup MVP scrape could be used in comparing team track records and winning capabilities
8. Interesting review of ROI and fan engagement if using MLS Cup MVP award and initial data table from scraping (Note: No dataframe created at this time)
9. Further granularity in 'Player of the Month' awards: Total monthly count of player receiving award in a given year 
10. Golden Boot award difference between >2005 and from 2005 onward - calculated differently latter takes a rate based on games => Feature Engineering
11. Consider cutting it at 2005+ to reflect difference in league and changes to the league